services:
  - type: web
    name: lector-imagenes
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr tesseract-ocr-spa && \
      pip install -r requirements.txt
    startCommand: gunicorn lector_api.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
